### ISSUE TITLE
[v1.1.1] Version in module.info not up to date

### ISSUE THREAD

**Issue by NicolasGoeddel** [Icinga/icingaweb2-module-cube#77] opened 2021-12-17 14:14 UTC
## Describe the bug
In release `1.1.1` the version string within `module.info` was not upgraded. It still shows `1.1.0`.

I don't think there is anything more to mention here.

**Comment by nilmerg** [comment] 2021-12-17 14:51
Duplicate of #59

**Closed by nilmerg** 2021-12-17 14:51 UTC
