### ISSUE TITLE
Version number not incremented in module.info for v1.1.1 release

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [Icinga/icingaweb2-module-cube#61] opened 2020-07-15 23:01 UTC
## Describe the bug
After installing Cube 1.1.1 the version number still shows as 1.1.0. The only place I can find the number is in `./module.info`.

## To Reproduce

1. Install `icingaweb2-module-cube` v1.1.1.
1. Enable module using `icingacli module enable cube`.
1. Examine version using `icingacli module list | grep cube`.

## Expected behavior
Expected:

    cube           1.1.1     enabled   Cube for Icinga Web 2

Actual:

    cube           1.1.0     enabled   Cube for Icinga Web 2

## Your Environment
* Icinga Web 2: v2.7.3
* Cube: v1.1.1

## Additional context
This is confusing for the installer because it is not clear that the new version of the module has been installed.
This could also confuse configuration management if it thinks that the module needs to be upgraded when it already has been.

**Comment by sukhwinder33445** [comment] 2021-07-05 14:35
duplicate of #59

**Closed by sukhwinder33445** 2021-07-05 14:35 UTC
