### ISSUE TITLE
Allow filtering on default variable / objects

### ISSUE THREAD

**Issue by HOSTED-POWER** [Icinga/icingaweb2-module-cube#83] opened 2022-04-14 08:55 UTC
We were testing this module, but feeling a bit limited to the custom variables only.

Why not select all services with names that start with "disk-*" for example , or how to filter on certain states and other existing objects.

Do you guys see a use case for this as well ?

**Comment by nilmerg** [comment] 2022-12-05 08:27
Duplicate of #16.

**Closed by nilmerg** 2022-12-05 08:27 UTC
