### ISSUE TITLE
Cube: Trait 'Icinga\\Module\\Icingadb\\Common\\Auth' not found in ...

### ISSUE THREAD

**Issue by pluhin** [Icinga/icingaweb2-module-cube#137] opened 2023-05-12 12:37 UTC
## Describe the bug

Hello Team.

After last redeployment Icingaweb2 i have the following error for module cube:

```
[Fri May 12 12:23:56.385824 2023] [php7:error] [pid 24] [client 10.42.0.34:37476] PHP Fatal error:  Trait 'Icinga\\Module\\Icingadb\\Common\\Auth' not found in /usr/share/icingaweb2/modules/cube/library/Cube/IcingaDb/CustomVariableDimension.php on line 15, referer: http://icinga-ui-lab-lgi.obo.libgbl-lab.biz/cube/services
[Fri May 12 12:23:56.386469 2023] [php7:notice] [pid 24] [client 10.42.0.34:37476] icingaweb2: ERROR - ErrorException in /usr/share/icingaweb2/modules/cube/library/Cube/IcingaDb/CustomVariableDimension.php:15 with message: Trait 'Icinga\\Module\\Icingadb\\Common\\Auth' not found\n#0 [internal function]: Icinga\\Application\\Web->Icinga\\Application\\{closure}()\n#1 {main}, referer: http://icinga-ui-lab-lgi.obo.libgbl-lab.biz/cube/services
```

## To Reproduce

I rebuild official images, added only RUN with google-chrome-stable installation, please see section below

```Dockerfile
....
RUN ["bash", "-exo", "pipefail", "-c", "export DEBIAN_FRONTEND=noninteractive; apt-get update; apt-get install --no-install-{recommends,suggests} -y apache2 ca-certificates libapache2-mod-php7.4 libldap-common locales-all php-{imagick,redis} php7.4-{bcmath,bz2,common,curl,dba,enchant,gd,gmp,imap,interbase,intl,json,ldap,mbstring,mysql,odbc,opcache,pgsql,pspell,readline,snmp,soap,sqlite3,sybase,tidy,xml,xmlrpc,xsl,zip}; apt-get clean; rm -vrf /var/lib/apt/lists/*"]
############# NEW LINES #####################
RUN export DEBIAN_FRONTEND=noninteractive &&  apt-get update \
    && apt-get install -y apt-transport-https gnupg wget \
    && wget -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
    && apt-get update && apt-get install -y google-chrome-stable \
    && apt-get clean && rm -vrf /var/lib/apt/lists/*
############# ######### #####################
COPY --from=entrypoint /entrypoint/entrypoint /entrypoint
....
```

When I tried to choice  any dimensions have error

![image](https://github.com/Icinga/icingaweb2-module-cube/assets/8258487/b72d2d42-272b-41a0-b2d1-7256c05dab3c)
  

## Expected behavior

Module works

## Screenshots

![image](https://github.com/Icinga/icingaweb2-module-cube/assets/8258487/929d9db6-cdf5-4909-bd28-104efb9fe689)

folder icingaweb2

```
www-data@icingaweb2-64f86bd8bc-4586q:/$ ls -l /data/etc/icingaweb2/
total 40
-rwxrwxrwx 1 www-data www-data   51 Apr  6 11:20 authentication.ini
-rwxrwxrwx 1 www-data www-data  179 Apr 26 12:04 config.ini
drwxrwsrwx 4 www-data www-data 4096 Oct 15  2021 dashboards
drwxr-x--- 2 www-data www-data 4096 May 12 12:04 enabledModules
-rwxrwxrwx 1 www-data www-data   51 Apr  6 11:20 groups.ini
drwxrwxrwx 6 www-data www-data 4096 May  1 12:35 modules
drwxrws--- 2 www-data www-data 4096 Nov  4  2019 navigation
drwxrwsrwx 4 www-data www-data 4096 Dec 12  2019 preferences
-rwxrwxrwx 1 www-data www-data  450 Apr  6 11:20 resources.ini
-rwxrwxrwx 1 www-data www-data  437 May 12 11:54 roles.ini
```

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.11.4
* Web browser used: Edge/Chrome
* Icinga 2 version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.0-1)
* PHP version used (`php --version`): 7.4.33
* Server operating system and version: Debian GNU/Linux 11 (bullseye)

## Additional context

Used docker image:
https://github.com/Icinga/docker-icingaweb2/blob/master/Dockerfile

**Comment by sukhwinder33445** [comment] 2023-06-05 07:44
duplicate of #131

**Closed by sukhwinder33445** 2023-06-05 07:44 UTC
